env:
  browser: true
  node: true
  es2021: true
extends:
  - 'plugin:vue/vue3-recommended'
  - 'eslint:recommended'
  - '@vue/typescript/recommended'
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
rules:
  indent: ['error', 2]
  vue/script-indent: ['error', 2]
  vue/html-indent: ['error', 2]
  no-undef: 'off'
  vue/multi-word-component-names: 'off'
  vue/max-attributes-per-line: 'off'
  vue/singleline-html-element-content-newline: 'off'
  vue/html-self-closing: [error, html: { void: always }]
  '@typescript-eslint/no-namespace': 'off'
